"use client";

import { loader, type Monaco } from "@monaco-editor/react";

// Monaco is copied into /public by scripts/copy-monaco.mjs, so the editor
// never depends on a third-party CDN.
loader.config({ paths: { vs: "/monaco/vs" } });

let themesDefined = false;

/**
 * Editor colour schemes modelled on the JetBrains New UI "Dark" and "Light"
 * schemes: warm keywords, green strings, cyan numbers, grey comments.
 */
export function defineThemes(monaco: Monaco) {
  if (themesDefined) return;
  themesDefined = true;

  monaco.editor.defineTheme("cw-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "bcbec4" },
      { token: "comment", foreground: "7a7e85" },
      { token: "comment.doc", foreground: "5f826b", fontStyle: "italic" },
      { token: "keyword", foreground: "cf8e6d" },
      { token: "string", foreground: "6aab73" },
      { token: "string.escape", foreground: "cf8e6d" },
      { token: "number", foreground: "2aacb8" },
      { token: "type", foreground: "bcbec4" },
      { token: "type.identifier", foreground: "bcbec4" },
      { token: "identifier", foreground: "bcbec4" },
      { token: "annotation", foreground: "b3ae60" },
      { token: "delimiter", foreground: "bcbec4" },
      { token: "delimiter.curly", foreground: "bcbec4" },
      { token: "delimiter.parenthesis", foreground: "bcbec4" },
      { token: "delimiter.square", foreground: "bcbec4" },
      { token: "delimiter.bracket", foreground: "bcbec4" },
      { token: "delimiter.angle", foreground: "bcbec4" },
      { token: "operator", foreground: "bcbec4" },
      { token: "regexp", foreground: "42c3d4" },
      { token: "tag", foreground: "d5b778" },
    ],
    colors: {
      "editor.background": "#1e1f22",
      "editor.foreground": "#bcbec4",
      "editorBracketHighlight.foreground1": "#bcbec4",
      "editorBracketHighlight.foreground2": "#bcbec4",
      "editorBracketHighlight.foreground3": "#bcbec4",
      "editorBracketHighlight.foreground4": "#bcbec4",
      "editorBracketHighlight.foreground5": "#bcbec4",
      "editorBracketHighlight.foreground6": "#bcbec4",
      "editorBracketHighlight.unexpectedBracket.foreground": "#bcbec4",
      "editorLineNumber.foreground": "#4b5059",
      "editorLineNumber.activeForeground": "#a1a3ab",
      "editor.lineHighlightBackground": "#26282e",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#214283",
      "editor.inactiveSelectionBackground": "#2a3a5c",
      "editor.selectionHighlightBackground": "#373b39",
      "editor.wordHighlightBackground": "#373b39",
      "editor.findMatchBackground": "#32593d",
      "editor.findMatchHighlightBackground": "#2c4a36",
      "editorCursor.foreground": "#ced0d6",
      "editorIndentGuide.background1": "#313438",
      "editorIndentGuide.activeBackground1": "#4b5059",
      "editorWhitespace.foreground": "#3a3d41",
      "editorGutter.background": "#1e1f22",
      "editorWidget.background": "#2b2d30",
      "editorWidget.border": "#43454a",
      "editorSuggestWidget.background": "#2b2d30",
      "editorSuggestWidget.border": "#43454a",
      "editorSuggestWidget.selectedBackground": "#2e436e",
      "editorHoverWidget.background": "#2b2d30",
      "editorHoverWidget.border": "#43454a",
      "input.background": "#1e1f22",
      "input.border": "#4e5157",
      "focusBorder": "#3574f0",
      "list.hoverBackground": "#393b40",
      "list.activeSelectionBackground": "#2e436e",
      "scrollbarSlider.background": "#ffffff14",
      "scrollbarSlider.hoverBackground": "#ffffff24",
      "scrollbarSlider.activeBackground": "#ffffff30",
      "minimap.background": "#1e1f22",
      "editorBracketMatch.background": "#43454a",
      "editorBracketMatch.border": "#00000000",
      "editorError.foreground": "#f75464",
      "editorWarning.foreground": "#e0bb65",
      "editorInfo.foreground": "#548af7",
      "editorOverviewRuler.border": "#00000000",
      "editorStickyScroll.background": "#1e1f22",
      "editorStickyScrollHover.background": "#26282e",
    },
  });

  monaco.editor.defineTheme("cw-light", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "080808" },
      { token: "comment", foreground: "8c8c8c", fontStyle: "italic" },
      { token: "keyword", foreground: "0033b3" },
      { token: "string", foreground: "067d17" },
      { token: "string.escape", foreground: "0037a6" },
      { token: "number", foreground: "1750eb" },
      { token: "type", foreground: "000000" },
      { token: "type.identifier", foreground: "000000" },
      { token: "identifier", foreground: "080808" },
      { token: "annotation", foreground: "9e880d" },
      { token: "delimiter", foreground: "080808" },
      { token: "delimiter.curly", foreground: "080808" },
      { token: "delimiter.parenthesis", foreground: "080808" },
      { token: "delimiter.square", foreground: "080808" },
      { token: "delimiter.bracket", foreground: "080808" },
      { token: "delimiter.angle", foreground: "080808" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#080808",
      "editorBracketHighlight.foreground1": "#080808",
      "editorBracketHighlight.foreground2": "#080808",
      "editorBracketHighlight.foreground3": "#080808",
      "editorBracketHighlight.foreground4": "#080808",
      "editorBracketHighlight.foreground5": "#080808",
      "editorBracketHighlight.foreground6": "#080808",
      "editorBracketHighlight.unexpectedBracket.foreground": "#080808",
      "editorLineNumber.foreground": "#aeb3c2",
      "editorLineNumber.activeForeground": "#767a8a",
      "editor.lineHighlightBackground": "#f5f8fe",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#a6d2ff",
      "editor.inactiveSelectionBackground": "#d5e4fb",
      "editorCursor.foreground": "#000000",
      "editorIndentGuide.background1": "#ebecf0",
      "editorIndentGuide.activeBackground1": "#c9ccd6",
      "editorGutter.background": "#ffffff",
      "editorWidget.background": "#ffffff",
      "editorWidget.foreground": "#1e1f22",
      "editorWidget.border": "#c9ccd6",
      // Autocomplete, hovers and lists: set every colour, or Monaco keeps its white selected text.
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#c9ccd6",
      "editorSuggestWidget.foreground": "#1e1f22",
      "editorSuggestWidget.selectedBackground": "#d4e2ff",
      "editorSuggestWidget.selectedForeground": "#1e1f22",
      "editorSuggestWidget.selectedIconForeground": "#1e1f22",
      "editorSuggestWidget.highlightForeground": "#1750eb",
      "editorSuggestWidget.focusHighlightForeground": "#1750eb",
      "editorHoverWidget.background": "#ffffff",
      "editorHoverWidget.foreground": "#1e1f22",
      "editorHoverWidget.border": "#c9ccd6",
      "list.activeSelectionBackground": "#d4e2ff",
      "list.activeSelectionForeground": "#1e1f22",
      "list.activeSelectionIconForeground": "#1e1f22",
      "list.inactiveSelectionBackground": "#e8ecf5",
      "list.inactiveSelectionForeground": "#1e1f22",
      "list.focusBackground": "#d4e2ff",
      "list.focusForeground": "#1e1f22",
      "list.hoverBackground": "#ebecf0",
      "list.hoverForeground": "#1e1f22",
      "list.highlightForeground": "#1750eb",
      "quickInput.background": "#ffffff",
      "quickInput.foreground": "#1e1f22",
      "quickInputList.focusBackground": "#d4e2ff",
      "quickInputList.focusForeground": "#1e1f22",
      "focusBorder": "#3574f0",
      "minimap.background": "#ffffff",
      "editorBracketMatch.background": "#d3d5db",
      "editorBracketMatch.border": "#00000000",
      "editorOverviewRuler.border": "#00000000",
    },
  });
}

/** Monaco model URI for a project file. Keeping one model per file preserves undo history across tabs. */
export function modelUri(monaco: Monaco, projectId: string, path: string) {
  return monaco.Uri.parse(`file:///${projectId}/${path}`);
}
